import type { Metadata } from "next";
import { Geist, Geist_Mono, Orbitron } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const orbitron = Orbitron({
    variable: "--font-orbitron",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${orbitron.variable} antialiased relative min-h-screen`}
            >
                {/* ✅ Vaste achtergrond */}
                <div className="fixed inset-0 -z-10 bg-[url('/bg.avif')] bg-cover bg-center" />

                {/* ✅ Inhoud erbovenop */}
                {children}
            </body>
        </html>
    );
}
